# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cavendish Allotments
email: enquiries@cavendish-allotments.org.uk
description: > # this means to ignore newlines until "baseurl:"
  The website of the Cavendish House Allotments in St Margarests, Greater London.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.cavendish-allotments.org.uk" # the base hostname & protocol for your site
twitter_username: stmgrts
github_username:  pmahnke

exclude:
    - node_modules

# gems
gems:
  - jekyll-archives
  - jekyll-textile-converter

# Build settings
markdown: kramdown
textile_ext: "textile,txtl,tl"
sass:
    style: compressed
    sass_dir: _sass

jekyll-archives:
  enabled:
    - year
    - month
    - categories
  layouts:
    year: year-archive
    month: month-archive
    category: category-archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    category: '/:name/'
